export const SET_LOGIN_DATA = "SET_LOGIN_DATA";
export const VERIFY_CODE_POST_HAS_ERROR = "VERIFY_CODE_POST_HAS_ERROR";
export const LOGIN_POST_HAS_ERROR = "LOGIN_POST_HAS_ERROR";
export const SET_IS_APP_LOADING = "SET_IS_APP_LOADING";
